export const DROPDOWN_BUTTON = "inline-flex items-center gap-2 px-3 py-2 bg-gray-100 rounded-lg hover:bg-gray-200 disabled:bg-gray-400 disabled:cursor-not-allowed disabled:opacity-60" ;
export const TIME_BTN = "px-3 py-2 rounded-md border text-left";
export const TIME_BTN_DISABLED = `${TIME_BTN} pointer-events-none opacity-50`;
export const TIME_BTN_ACTIVE =`${TIME_BTN} active:bg-blue-600 active:text-white active:scale-95 transition`;
export const STATUS_BUTTON = "inline-block rounded-full px-6 pb-2 pt-2.5 text-xs font-medium uppercase leading-normal text-white shadow-primary-3 transition duration-150 ease-in-out focus:bg-primary-accent-300 focus:shadow-primary-2 focus:outline-none focus:ring-0 active:bg-primary-600 active:shadow-primary-2 motion-reduce:transition-none dark:shadow-black/30 dark:hover:shadow-dark-strong dark:focus:shadow-dark-strong dark:active:shadow-dark-strong"
export const BOOKED = "bg-green-400 hover:bg-green-500";
export const DANGER = "bg-red-400 hover:bg-red-500";
export const COMPLETED = "bg-blue-600 hover:bg-blue-700";
export const UNSELECTED = "bg-gray-300 hover:bg-gray-400";